[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = {version = "0.5.0-rc.2", features = ["json"]}
rocket_cors = "0.6.0"
serde = "1.0.136"
dotenv = "0.15.0"
serde_json = "1.0.141"
chrono = { version = "0.4.41", features = ["serde"] }

[dependencies.mongodb]
version = "2.2.0"
default-features = false
features = ["sync"] 
